[package]
name = "cpu_monitor"
version = "0.1.0"
edition = "2024"

[dependencies]
sysinfo = "0.30"
nvml-wrapper = "0.10"
tui = "0.19"
crossterm = "0.27"
ratatui = "0.26"
chrono = "0.4"
regex = "1.10"
